apiVersion: v1
kind: Pod
metadata:
  name: podName
spec:
  containers:
  - name: podName
    image: image:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        add: ["IPC_LOCK"]
  restartPolicy: Never